config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  get 'sessions/new'

  resources :sessions, only: [:new, :create, :destroy]
  resources :pictures do 
    collection do 
      post :confirm
      get :list
      post :list
    end 
  end
  
  resources :users, only: [:new, :show, :create, :edit, :confirm, :update] do
    collection do
      post :confirm
    end
  end
  
  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
  belongs_to :user
  belongs_to :picture
  
  
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
    
  validates :image, presence: true
  validates :content, presence: true
    
  belongs_to :user
    
    
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
end

app/models/user.rb
class User < ApplicationRecord
  validates:name,  presence:true, length:{ maximum:30 }
  validates:email, presence:true, length:{ maximum:255 },
                  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
 
  before_validation {email.downcase! }               
         
  has_secure_password
  validates:password,presence:true,length:{ minimum:3 }
  
  mount_uploader :image, ImageUploader
  
  has_many :pictures
  has_many :favorites, dependent: :destroy
 
  #has_many :favorite_pictures, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
  #Applicationコントローラにこのモジュールをインクルードする（含める）ことによって、
  #Railsの全コントローラでこのモジュールが使用できるようになるので、設定しておきます。
  # application_contoroller에서include SessionsHelper하면어디서든 sessionhelper를 사용가능하다 이거다이
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "お気に入り解除しました"
  end
  
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action:checkSession, only: [:new, :edit, :show, :destroy, :list]
  
  before_action:set_pictures, only: [:destroy, :edit, :update, :show]
  
  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @pictures = Picture.new(pictures_params)  
    else
      @pictures = Picture.new
    end
  end

  def confirm
    @pictures = Picture.new(pictures_params)
    @pictures.user_id = current_user.id 
    p @pictures
    
  end

  def create
    @pictures = Picture.new(pictures_params)  
    @pictures.user_id = current_user.id
    if @pictures.user_id == current_user.id
      if @pictures.save
        #PictureMailer.picture_mail(@pictures).deliver
        redirect_to pictures_path
      else
        render 'new'
      end
    else
      flash[:notice] = "投稿権限がありません"
      redirect_to pictures_path  
    end
  end


  def show 
    p @pictures
    @favorite = current_user.favorites.find_by(picture_id: @pictures.id)
  end

  def destroy
    @pictures.destroy
    redirect_to pictures_path, notice: "insta削除完了。"
  end
  
  def edit
    p @pictures
  end
 
  def update
    p @pictures
    if @pictures.user_id == current_user.id
      if @pictures.update(pictures_params)
        redirect_to pictures_path, notice:'insta修正完了。'
      else
        render :edit  if @pictures.invalid?
      end 
    else
      flash[:notice] = "投稿編集の権限がありません"
      redirect_to pictures_path
    end
    
  end
  
  def list
    @favorites = Favorite.where(user_id: current_user.id)
    p @favorites
  end
  
  
  private
  
  def checkSession
    if !(session[:user_id])
      redirect_to new_session_path, notice:'loginしてください。'
    end 
  end
  
  def pictures_params
    params.require(:picture).permit(:content, :image, :image_cache)
  end

  def set_pictures 
    @pictures = Picture.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy 
    session.delete (:user_id)
    flash[:notice] = 'ログアウートしました。'
    redirect_to new_session_path
  end 
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    puts("@@@@@@@@@@@")
    @user = User.new
    p @user
  end
    
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice:"ログインしてください"
    else
      render '/users/new'
    end
  end
    
  def show 
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(current_user.id)
    p @user
  end
  
  def update
    @user = User.find(params[:id])
    p @user
    if @user.update(update_user_params)
      redirect_to user_path, notice:'個人情報修正完了。'
    else
      render :edit  if @user.invalid?
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
   
  def update_user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :image)
  end
  
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def  choose_new_or_edit 
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end 
  end 
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  #またユーザーがログインしていればtrue、その他ならfalseを返すメソッドも定義します。
  def logged_in?
    current_user.present?
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Songstagram</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-default">
    <marquee behavior="alternate" direction="up" width="670" height="70"  scrollamount="8"><marquee behavior="alternate" scrollamount="4">ようこそ、SONGSTAGRAMへ　＾＿＾</marquee></marquee>  
    <div>
      <ul >
        <li><%= link_to 'HOME','/'%></li>
        <% if logged_in? %>
          <li><%= link_to "Profile", user_path(current_user.id) %></li>
          <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
        <% else %>
         <li><%= link_to "Sign up", new_user_path %></li>
         <li><%= link_to "Login", new_session_path %></li>
       <% end %>
         <li><%= link_to 'Songsta作成','/pictures/new'%></li>
         <li><%= link_to 'GotoSongstagram','https://www.instagram.com/92_songsugeun/' %></li>
      </ul>
    </div>
    
  </div>
</nav>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    
    
    <%= yield %>
    
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @pictures, url: choose_new_or_edit, local: true) do |f| %>  
  <table class ='imageadd'>
    <tr>
      <td><%= image_tag(@pictures.image.url) if @pictures.image.url %></td>
    </tr>
    <tr>
      <td><%= f.label :image %></td>
      <td><%= f.file_field :image %></td>
    </tr>
    <tr>
      <td><%= f.label :content %></td>
      <td><%= f.text_field :content %></td>
    </tr>
    <tr>
      <td colspan ='2'><%= f.submit "登録" %></td>
    </tr>
  </table>
<% end %>

app/views/pictures/confirm.html.erb
<h1>確認画面</h1>
<div class ='imageadd'>
<%= form_with(model: @pictures, url: pictures_path, local: true) do |f| %>  
  <table >
    <tr>
      <td><%= image_tag (@pictures.image.url) %></td>
      <td><%= f.hidden_field :image, value: @pictures.image %></td>
      <td><%= f.hidden_field :image_cache %></td>
    </tr>
    <tr>
      <td><%= @pictures.content %></td>
      <td><%= f.hidden_field :content, value: @pictures.content %></td>
    </tr>
    <tr>
      <td colspan ='2'><%= f.submit "登録" %></td>
    </tr>
  </table>
<% end %>
</div>

<%= form_with(model: @pictures, url: new_picture_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :image_cache %> 
  <%= form.hidden_field :content %>
  <%= form.submit "back up", name: 'back' %>
<% end %> 

app/views/pictures/edit.html.erb
<h1>edit page</h1>
<%= render 'form' %>

app/views/pictures/index.html.erb
<% if @pictures.present? %>
<% @pictures.each do |picture| %>
  <div class="col-sm-6 col-md-3 col-xs-12">
    <table>
      <tr>
        <td class= 'show_table_honbunTH'  colspan='2'>作成者</td>
      </tr>
      <tr>
        <td colspan='2'><%= picture.user.name %></td>
      </tr>
      <tr class ="birdscontent">
        <% if picture.image != nil %> 
          <th  colspan='2'><%= image_tag (picture.image) %></th>
        <% end %>    
      </tr>
      <tr>
        <th class= 'show_table_honbunTH' , colspan='2'>内容</th>
      </tr>
      <tr>
        <td colspan='2'><%= link_to picture.content , picture_path(picture.id) %></td>
      </tr>
      <% if current_user.present? %>
        <% if picture.user_id == current_user.id %>
          <tr class ="buttonimageclass">
            <td colspan='1'><%= link_to '編集' , edit_picture_path(id: picture.id), data:{confirm: "本当に編集しますか"} %></td>
            <td colspan='1'><%= link_to '削除' , picture_path(picture.id), method: :delete, data:{confirm: "本当に削除しますか"} %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
<% end %>
<% else %>
  <h1>掲示物がありません、投稿してください。</h1>
<% end %>

app/views/pictures/list.html.erb
<% if @favorites.present? %>
  <% @favorites.each do |favorites| %>
    <div class="col-sm-6 col-md-3 col-xs-12">
      <table>
        <tr>
          <td>作成者</td>
        </tr>
        <tr>
          <td><%= favorites.picture.user.name %></td>
        </tr>
        <tr>
          <th class= 'show_table_honbunTH' colspan='2'>Content</th>
        </tr>
        <tr class ="birdscontent">
            <th  colspan='2'><%= image_tag (favorites.picture.image.url) %></th>
        </tr>
        <tr class ="birdscontent">  
          <th colspan='2'><%= favorites.picture.content %></th>
        </tr>
      </table>
    </div>
  <% end %>
<% else %>
  <h1>登録されたお気に入りがありません。</h1>
<% end %>

app/views/pictures/new.html.erb
<h1>insata投稿</h1>
<%= render 'form'%>

app/views/pictures/show.html.erb
<div class ='imageadd'>
  <table>
     <tr>
      <td>投稿日</td>
    </tr>
    <tr>
      <td><%= @pictures.created_at %></th>
    </tr>
    <tr>
      <td><%= image_tag @pictures.image.url %></td>
    </tr>
    <tr>
      <td><%= @pictures.content %></td>
    </tr>
    <tr>
    <% unless @pictures.user_id == current_user.id %> 
      <% if @favorite.present? %>
        <td><%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %></td>
      <% else %>
        <td><%= link_to 'お気に入りする', favorites_path(picture_id: @pictures.id), method: :post, class: 'btn btn-primary' %></td>
      <% end %>
    <% end %>
    </tr>
  </table>
  
  
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class ='newusertable'>
<%= form_with(model: @user, local: true) do |f| %>  
  <table class ='imageadd'>
    <tr>
        <% if @user.image.blank? %>
          <td><%= f.label :image %></td>
          <td><%= f.file_field :image %></td>
        <% else %>
        <tr>
          <td colspan='2'><%= image_tag (@user.image.url) %></td>
        </tr>
        <tr>
          <td><%= f.label :image %></td>
          <td><%= f.file_field :image %></td>
        </tr>
        <% end %>
    </tr>
    <tr>
      <td><%= f.label :name %></td>
      <% if @user.name.blank?%>
        <td><%= f.text_field :name %></td>
      <% else %>
        <td><%= f.text_field :name, value: @user.name %></td>
      <% end %>
    </tr>
    <tr>
      <td><%= f.label :email %></td>
      <% if @user.email.blank? %>
        <td><%= f.email_field :email %></td>
      <% else %>
        <td><%= f.email_field :email, :readonly => true ,value: @user.email %>IDは変更ｘ</td>
      <% end %>
    </tr>
    <tr>
      <td><%= f.label :password %></td>
      <% if @user.password.blank? %>
        <td><%= f.password_field :password %></td>
      <% else %>
        <td><%= f.hidden_field :password, value: @user.password %></td>
      <% end %>
    </tr>
    <tr>
      <td><%= f.label :password_confirmation %></td>
      <td><%= f.password_field :password_confirmation , value: @user.password %></td>
    </tr>
    <tr>
      <td colspan ='2'><%= f.submit "Create my account" %></td>
    </tr>
  </table>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>user edit page</h1>
<%= render 'form'%>

app/views/users/new.html.erb
<h1>user Sign up</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<%= image_tag @user.image.url %>
<h1><%= @user.name %>のページ</h1><hr>
<h3>Email : <%= @user.email %></h3>
<h2>貴方は<%= @user.id %>番目の会員です.</h2>
<h2>加入日<%= @user.created_at %>.</h2>

<% if logged_in? %>
  <h3><%= link_to 'ユーザ情報編集', edit_user_path, class: 'btn btn-danger' %></h3> 
  <h3><%= link_to 'お気に入り一覧', list_pictures_path , class: 'btn btn-danger' %></h3>
<% else %>
  <h1>ログインして</h1>
<% end %>